apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://localhost:8123
    jsonData:
      defaultDatabase: techlog
      port: 8123
      username: default
    secureJsonData:
      password: ''
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    database: monitoring
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    editable: true
